smtp:
  host: smtp.sendgrid.net
  port: 587
  secure: false
  auth:
    user: apikey
    pass: your_api_key
from: noreply@b-shock.org
element:
  url: https://matrix.b-shock.org
homeserver:
  url: https://synapse.b-shock.org
